language: node_js
cache: yarn
sudo: false
addons:
  code_climate:
    repo_token: d3d40174fa6772b8d690d2e5af5fb54975f12bbb6291efa2998eb1da87f60f90
node_js:
  - "9"
  - "10"
  - "11"
script:
  - yarn test --coverage
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
