export const ORIOLE_SEARCH = '@@oriole/SEARCH'
export const ORIOLE_FETCH = '@@oriole/FETCH'
export const ORIOLE_FETCH_BEGIN = '@@oriole/FETCH_BEGIN'
export const ORIOLE_FETCH_SUCCESS = '@@oriole/FETCH_SUCCESS'
export const ORIOLE_FETCH_ERROR = '@@oriole/FETCH_ERROR'
export const ORIOLE_FETCH_CANCEL = '@@oriole/FETCH_CANCEL'